name: "Mayastor tests"
on:
  pull_request:
    paths-ignore:
      - 'csi/moac/**'
      - 'doc/**'
jobs:
  Build:
    name: Build and run tests
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:nix
      options: --privileged -v /dev:/dev -v /bin:/host/bin -v /lib/modules:/lib/modules --cpus 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          # this does not pin the compiler version
          toolchain: stable
      - run: ln -s /host/bin/kmod /bin/modprobe
      - run: /bin/modprobe nbd
      - run: /bin/modprobe xfs
      - run: echo 1024 | tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
      - run: rm mayastor/.cargo/config
      - run: cargo build --all
      - run: ( cd jsonrpc && cargo test )
      - run: ( cd mayastor && cargo test -- --test-threads=1 )
      - run: ( cd mayastor-test && npm install && ./node_modules/mocha/bin/mocha test_cli.js )
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_replica.js )
      - run: ( cd mayastor-test && TEST_PORT=10125 ./node_modules/mocha/bin/mocha test_replica.js )
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_csi.js )
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_nexus.js )
      - run: ( cd mayastor-test && TEST_PORT=10125 ./node_modules/mocha/bin/mocha test_nexus.js )
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_rebuild.js )
      - run: ( cd mayastor-test && TEST_PORT=10125 ./node_modules/mocha/bin/mocha test_rebuild.js )
      - run: ( cd nvmeadm && cargo test )
  Image:
    # dont image if the build fails
    needs: Build
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v7
      - uses: cachix/cachix-action@v5
        with:
          name: mayastor
          skipNixBuild: true
      - run: nix-build -A mayastorImage -o /tmp/mayastorImage
      - run: nix-build -A mayastorCSIImage -o /tmp/mayastorCSIImage
  ms-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v7
      - uses: cachix/cachix-action@v5
        with:
          name: mayastor
          attributes: ms-buildenv
